-- Queue Codex recipe recommendations on the trusted Mac and retain the xBloom
-- share URL generated by the official app after a recipe is saved.

ALTER TABLE bridge_jobs ADD COLUMN share_link TEXT;

CREATE TABLE recommendation_jobs (
  id               TEXT    NOT NULL PRIMARY KEY,
  owner_id         TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  username_display TEXT    NOT NULL,
  bean_name        TEXT    NOT NULL,
  bean_json        TEXT    NOT NULL,
  brew_mode        TEXT    NOT NULL CHECK (brew_mode IN ('cold', 'hot')),
  status           TEXT    NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'claimed', 'completed', 'failed')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  claimed_at       INTEGER,
  recipe_id        TEXT    REFERENCES recipes(id) ON DELETE SET NULL,
  safe_error       TEXT,
  created_at       INTEGER NOT NULL,
  updated_at       INTEGER NOT NULL,
  completed_at     INTEGER
);

CREATE INDEX recommendation_jobs_status ON recommendation_jobs(status, created_at);
CREATE INDEX recommendation_jobs_owner_id ON recommendation_jobs(owner_id, created_at DESC);
